package com.aed.pathfinder.views;

import com.aed.pathfinder.util.CustomHeaderRenderer;
import com.aed.pathfinder.util.CustomTreeCellRenderer;
import com.formdev.flatlaf.IntelliJTheme;
import java.awt.Color;
import java.awt.Dimension;
import static java.lang.StringTemplate.STR;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.TableColumn;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Juan Romero Collazos
 */
public class PathFinder extends javax.swing.JFrame {
    private static final Logger LOGGER = Logger.getLogger(PathFinder.class.getName());
    private boolean checkOpenTools = true;
    /**
     * Creates new form PathFinder
     */
    public PathFinder() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/favicon_main.png")).getImage());
        DefaultMutableTreeNode rootNode = (DefaultMutableTreeNode) tree.getModel().getRoot();
        rootNode.setUserObject("Unidad C:");
        CustomTreeCellRenderer rendererTree = new CustomTreeCellRenderer(null);
        tree.setCellRenderer(rendererTree);
        rendererTree.setRootIcon(new ImageIcon(getClass().getResource("/img/disco.png")));
        CustomTreeCellRenderer rendererAccesosDirectos = new CustomTreeCellRenderer(null);
        accesos_directos.setCellRenderer(rendererAccesosDirectos);
        rendererAccesosDirectos.setRootIcon(new ImageIcon(getClass().getResource("/img/acceso-directo-icon.png")));
        input_direccion.setText("C:\\");
        input_busqueda.putClientProperty( "JTextField.placeholderText", "Buscar aquí..." );
        input_busqueda.putClientProperty( "JComponent.roundRect", true );
        input_direccion.putClientProperty( "JComponent.roundRect", true );
        table_explorer.setShowGrid(true);
        table_explorer.setShowVerticalLines(true);
        table_explorer.setGridColor(Color.LIGHT_GRAY);
        for (int i = 0; i < table_explorer.getColumnModel().getColumnCount(); i++) {
            TableColumn column = table_explorer.getColumnModel().getColumn(i);
            column.setHeaderRenderer(new CustomHeaderRenderer());
        }
        cantidad_de_elementos.setText(STR."\{table_explorer.getRowCount()} elementos |");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barra_de_herramientas = new javax.swing.JPanel();
        btn_crear_carpeta = new javax.swing.JButton();
        btn_crear_unidad = new javax.swing.JButton();
        btn_crear_archivo_de_texto = new javax.swing.JButton();
        btn_renombrar = new javax.swing.JButton();
        btn_copiar = new javax.swing.JButton();
        btn_pegar = new javax.swing.JButton();
        btn_cortar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_acceso_directo = new javax.swing.JButton();
        btn_acceso_directo1 = new javax.swing.JButton();
        barra_de_direcciones = new javax.swing.JPanel();
        input_direccion = new javax.swing.JTextField();
        input_busqueda = new javax.swing.JTextField();
        btn_atras = new javax.swing.JButton();
        btn_adelante = new javax.swing.JButton();
        btn_inicio = new javax.swing.JButton();
        btn_una_carpeta_hacia_arriba = new javax.swing.JButton();
        btn_recargar = new javax.swing.JButton();
        btn_herramientas = new javax.swing.JButton();
        area_de_visulizacion_de_archivos = new javax.swing.JPanel();
        panel_de_archivos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        accesos_directos = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_explorer = new javax.swing.JTable();
        barra_de_estado = new javax.swing.JPanel();
        cantidad_de_elementos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btn_menu_archivo = new javax.swing.JMenu();
        btn_exportar = new javax.swing.JMenuItem();
        btn_importar = new javax.swing.JMenuItem();
        btn_guardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PathFinder");
        setMinimumSize(new java.awt.Dimension(906, 522));
        setPreferredSize(new java.awt.Dimension(930, 540));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        barra_de_herramientas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Herramientas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 149, 217))); // NOI18N
        barra_de_herramientas.setPreferredSize(new java.awt.Dimension(918, 100));

        btn_crear_carpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carpetas.png"))); // NOI18N
        btn_crear_carpeta.setToolTipText("Crear carpeta");
        btn_crear_carpeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_crear_unidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unidad.png"))); // NOI18N
        btn_crear_unidad.setToolTipText("Crear disco");
        btn_crear_unidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_crear_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_unidadActionPerformed(evt);
            }
        });

        btn_crear_archivo_de_texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo.png"))); // NOI18N
        btn_crear_archivo_de_texto.setToolTipText("Crear un archivo de texto");
        btn_crear_archivo_de_texto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_renombrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/renombrar-archivo.png"))); // NOI18N
        btn_renombrar.setToolTipText("Cambiar de nombre");
        btn_renombrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_copiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copiar.png"))); // NOI18N
        btn_copiar.setToolTipText("copiar");
        btn_copiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_pegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pegar.png"))); // NOI18N
        btn_pegar.setToolTipText("pegar");
        btn_pegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_cortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cortar.png"))); // NOI18N
        btn_cortar.setToolTipText("cortar");
        btn_cortar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btn_eliminar.setToolTipText("eliminar");
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_acceso_directo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acceso-directo.png"))); // NOI18N
        btn_acceso_directo.setToolTipText("crear acceso directo");
        btn_acceso_directo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_acceso_directo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/propiedades.png"))); // NOI18N
        btn_acceso_directo1.setToolTipText("Propiedades");
        btn_acceso_directo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout barra_de_herramientasLayout = new javax.swing.GroupLayout(barra_de_herramientas);
        barra_de_herramientas.setLayout(barra_de_herramientasLayout);
        barra_de_herramientasLayout.setHorizontalGroup(
            barra_de_herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_de_herramientasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_crear_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_crear_carpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_crear_archivo_de_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_renombrar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_copiar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pegar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cortar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_acceso_directo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_acceso_directo1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        barra_de_herramientasLayout.setVerticalGroup(
            barra_de_herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_de_herramientasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barra_de_herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_crear_unidad, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btn_crear_carpeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_crear_archivo_de_texto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_renombrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_copiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_pegar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cortar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_acceso_directo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_acceso_directo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(barra_de_herramientas);

        barra_de_direcciones.setPreferredSize(new java.awt.Dimension(918, 40));

        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_left.png"))); // NOI18N
        btn_atras.setBorderPainted(false);
        btn_atras.setContentAreaFilled(false);
        btn_atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_atras.setFocusPainted(false);

        btn_adelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_right.png"))); // NOI18N
        btn_adelante.setBorderPainted(false);
        btn_adelante.setContentAreaFilled(false);
        btn_adelante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adelante.setFocusPainted(false);

        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btn_inicio.setBorderPainted(false);
        btn_inicio.setContentAreaFilled(false);
        btn_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_inicio.setFocusPainted(false);

        btn_una_carpeta_hacia_arriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_up.png"))); // NOI18N
        btn_una_carpeta_hacia_arriba.setBorderPainted(false);
        btn_una_carpeta_hacia_arriba.setContentAreaFilled(false);
        btn_una_carpeta_hacia_arriba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_una_carpeta_hacia_arriba.setFocusPainted(false);

        btn_recargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload.png"))); // NOI18N
        btn_recargar.setBorderPainted(false);
        btn_recargar.setContentAreaFilled(false);
        btn_recargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_recargar.setFocusPainted(false);

        btn_herramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/herramientas.png"))); // NOI18N
        btn_herramientas.setBorderPainted(false);
        btn_herramientas.setContentAreaFilled(false);
        btn_herramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_herramientas.setFocusPainted(false);
        btn_herramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_herramientasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barra_de_direccionesLayout = new javax.swing.GroupLayout(barra_de_direcciones);
        barra_de_direcciones.setLayout(barra_de_direccionesLayout);
        barra_de_direccionesLayout.setHorizontalGroup(
            barra_de_direccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_de_direccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_adelante)
                .addGap(18, 18, 18)
                .addComponent(btn_inicio)
                .addGap(12, 12, 12)
                .addComponent(btn_una_carpeta_hacia_arriba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_recargar)
                .addGap(18, 18, 18)
                .addComponent(input_busqueda)
                .addGap(18, 18, 18)
                .addComponent(btn_herramientas)
                .addGap(18, 18, 18))
        );
        barra_de_direccionesLayout.setVerticalGroup(
            barra_de_direccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barra_de_direccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(barra_de_direccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_recargar)
                    .addComponent(btn_una_carpeta_hacia_arriba)
                    .addComponent(btn_inicio)
                    .addComponent(btn_adelante)
                    .addComponent(btn_atras)
                    .addComponent(input_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(barra_de_direccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_herramientas)
                        .addComponent(input_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(barra_de_direcciones);

        area_de_visulizacion_de_archivos.setLayout(new javax.swing.BoxLayout(area_de_visulizacion_de_archivos, javax.swing.BoxLayout.LINE_AXIS));

        panel_de_archivos.setLayout(new javax.swing.BoxLayout(panel_de_archivos, javax.swing.BoxLayout.PAGE_AXIS));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(99, 200));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Accesos directos");
        accesos_directos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(accesos_directos);

        panel_de_archivos.add(jScrollPane3);

        tree.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(tree);

        panel_de_archivos.add(jScrollPane1);

        area_de_visulizacion_de_archivos.add(panel_de_archivos);

        table_explorer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fecha de creación", "Fecha de modificación", "Tipo", "Tamaño"
            }
        ));
        jScrollPane2.setViewportView(table_explorer);

        area_de_visulizacion_de_archivos.add(jScrollPane2);

        getContentPane().add(area_de_visulizacion_de_archivos);

        barra_de_estado.setBackground(new java.awt.Color(0, 119, 232));
        barra_de_estado.setPreferredSize(new java.awt.Dimension(918, 20));

        cantidad_de_elementos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cantidad_de_elementos.setForeground(new java.awt.Color(255, 255, 255));
        cantidad_de_elementos.setText("0 elementos |");

        javax.swing.GroupLayout barra_de_estadoLayout = new javax.swing.GroupLayout(barra_de_estado);
        barra_de_estado.setLayout(barra_de_estadoLayout);
        barra_de_estadoLayout.setHorizontalGroup(
            barra_de_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_de_estadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cantidad_de_elementos)
                .addContainerGap(836, Short.MAX_VALUE))
        );
        barra_de_estadoLayout.setVerticalGroup(
            barra_de_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_de_estadoLayout.createSequentialGroup()
                .addComponent(cantidad_de_elementos)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(barra_de_estado);

        btn_menu_archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carpeta.png"))); // NOI18N
        btn_menu_archivo.setText("Archivo");
        btn_menu_archivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_archivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_exportar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_exportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exportar.png"))); // NOI18N
        btn_exportar.setText("Exportar");
        btn_exportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_archivo.add(btn_exportar);

        btn_importar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_importar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/importar.png"))); // NOI18N
        btn_importar.setText("Importar");
        btn_importar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_archivo.add(btn_importar);

        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu_archivo.add(btn_guardar);

        jMenuBar1.add(btn_menu_archivo);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_herramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_herramientasActionPerformed
        if (checkOpenTools) {
            barra_de_herramientas.setVisible(false);
            barra_de_herramientas.setPreferredSize(new Dimension(918, 0));
        } else {
            barra_de_herramientas.setVisible(true);
            barra_de_herramientas.setPreferredSize(new Dimension(918, 100));
        }
        checkOpenTools = !checkOpenTools;

        barra_de_herramientas.revalidate();
        barra_de_herramientas.repaint();
    }//GEN-LAST:event_btn_herramientasActionPerformed

    private void btn_crear_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_unidadActionPerformed
        CreateUnity createUnity = new CreateUnity();
        createUnity.setLocationRelativeTo(null);
        createUnity.setVisible(true);
    }//GEN-LAST:event_btn_crear_unidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            IntelliJTheme.setup(PathFinder.class.getResourceAsStream("/theme/DarkPurple.theme.json"));
            System.setProperty("flatlaf.menuBarEmbedded", "true");
            System.setProperty("flatlaf.useWindowDecorations", "true");
            System.setProperty("flatlaf.animation", "true");
            System.setProperty("flatlaf.useTextYCorrection", "true");
        } catch (Exception e) {
            LOGGER.severe(STR."Error: \{e}");
        }
        java.awt.EventQueue.invokeLater(() -> new PathFinder().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree accesos_directos;
    private javax.swing.JPanel area_de_visulizacion_de_archivos;
    private javax.swing.JPanel barra_de_direcciones;
    private javax.swing.JPanel barra_de_estado;
    private javax.swing.JPanel barra_de_herramientas;
    private javax.swing.JButton btn_acceso_directo;
    private javax.swing.JButton btn_acceso_directo1;
    private javax.swing.JButton btn_adelante;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_copiar;
    private javax.swing.JButton btn_cortar;
    private javax.swing.JButton btn_crear_archivo_de_texto;
    private javax.swing.JButton btn_crear_carpeta;
    private javax.swing.JButton btn_crear_unidad;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JMenuItem btn_exportar;
    private javax.swing.JMenuItem btn_guardar;
    private javax.swing.JButton btn_herramientas;
    private javax.swing.JMenuItem btn_importar;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JMenu btn_menu_archivo;
    private javax.swing.JButton btn_pegar;
    private javax.swing.JButton btn_recargar;
    private javax.swing.JButton btn_renombrar;
    private javax.swing.JButton btn_una_carpeta_hacia_arriba;
    private javax.swing.JLabel cantidad_de_elementos;
    private javax.swing.JTextField input_busqueda;
    private javax.swing.JTextField input_direccion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panel_de_archivos;
    private javax.swing.JTable table_explorer;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
}
